/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/maru_fixed.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/maru_fixed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="frame" geometry={nodes.frame.geometry} material={materials.Material} position={[0, 0.38, 1.73]} scale={[3.6, 3.6, 0.28]} />
        <group name="coffee" position={[0.5, -2.39, 1.8]} rotation={[0, -0.12, 0]} scale={[-0.4, -0.61, -0.39]}>
          <mesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={materials['Material.004']} />
          <mesh name="Cylinder004_1" geometry={nodes.Cylinder004_1.geometry} material={materials['Material.005']} />
        </group>
        <mesh name="wall" geometry={nodes.wall.geometry} material={materials.Material} position={[0, 0.38, 1.73]} scale={[3.6, 3.6, 0.28]} />
        <mesh name="body" geometry={nodes.body.geometry} material={materials.skin} position={[0, -2.91, -0.09]} scale={[2.06, 2.4, 1.7]} />
        <mesh name="ears" geometry={nodes.ears.geometry} material={materials.skin} position={[1.86, 0.38, 0.2]} rotation={[-Math.PI, 0, 0.37]} scale={[-0.18, -0.28, -0.18]} />
        <mesh name="eyes" geometry={nodes.eyes.geometry} material={materials['Material.001']} position={[0, 1.11, 1.59]} scale={[0.92, 0.97, 0.86]} />
        <mesh name="head_bottom" geometry={nodes.head_bottom.geometry} material={materials.skin} position={[0, 0.73, -0.09]} />
        <mesh name="mouth" geometry={nodes.mouth.geometry} material={materials['Material.002']} position={[0.01, 0.14, 1.67]} rotation={[0, 0, 0.01]} scale={[0.61, 0.32, 0.68]} />
        <mesh name="nose" geometry={nodes.nose.geometry} material={materials['Material.003']} position={[0, 0.76, 1.66]} scale={[0.22, 0.39, 0.16]} />
        <mesh name="head_top" geometry={nodes.head_top.geometry} material={materials.skin} position={[1.68, 1.53, 0.03]} />
        <mesh name="left_arm" geometry={nodes.left_arm.geometry} material={materials.skin} position={[1.72, -2.22, 0.36]} rotation={[-0.44, -0.16, 0.33]} scale={[0.39, 1.29, 0.36]} />
        <mesh name="right_arm" geometry={nodes.right_arm.geometry} material={materials.skin} position={[1.66, -2.24, 0.31]} rotation={[-0.49, -0.15, 0.32]} scale={[0.39, 1.29, 0.36]} />
        <mesh name="stem" geometry={nodes.stem.geometry} material={materials['Material.008']} position={[-1.67, -0.71, 1.74]} rotation={[-2, -1.2, 2.94]} />
        <mesh name="pot" geometry={nodes.pot.geometry} material={materials['Material.006']} position={[-1.67, -2.03, 1.83]} scale={0.71} />
        <mesh name="dirt" geometry={nodes.dirt.geometry} material={materials['Material.007']} position={[-1.67, -1.66, 1.83]} scale={0.71} />
        <mesh name="left_leaf" geometry={nodes.left_leaf.geometry} material={materials['Material.008']} position={[-1.67, -0.71, 1.74]} rotation={[1.51, -0.7, -0.11]} scale={[0.06, 0.25, 0.25]} />
        <mesh name="right_leaf" geometry={nodes.right_leaf.geometry} material={materials['Material.008']} position={[-1.67, -0.71, 1.74]} rotation={[1.15, 1.2, -2.92]} scale={[-0.05, -0.52, -0.16]} />
      </group>
    </group>
  )
}

useGLTF.preload('/maru_fixed.glb')
